version: "3"
services:

  browser:
    build:
      dockerfile: deployments/browser/Dockerfile
      context: . 
    container_name: "browser"
    command: ["--no-sandbox"]
    ports:
      - 9222:9222

#  go:
#    build:
#      dockerfile: build/Dockerfile
#      context: .
#    container_name: "spider_go"
#    env_file:
#        - environments/.env
#    ports:
#      - 9910:80
#    depends_on:
#      - browser
