version: "3"
services:

  browser:
    image: chromedp/headless-shell
    container_name: "browser"
    ports:
      - 9000:9222

  go:
    build:
      dockerfile: ./docker/go/Dockerfile
      context: ../.
    container_name: "spider_go"
    ports:
      - 9910:80
    volumes:
      - ../:/go/src/app
    depends_on:
      - browser
